apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployname }} #i27-eureka-dev
spec:
  selector:
    name: {{ .Values.labelname }} #i27-eureka
  type: NodePort # ClusterIP, NodePort, LoadBalancer
  ports:
  - protocol: TCP
    port: 80 # This is the service port 
    targetPort:  {{ .Values.targetPort}} # 8761